@Restaurants.API_HostAddress = https://localhost:7173


GET {{Restaurants.API_HostAddress}}/api/restaurants

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/3


###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Bella Italia",
  "description": "Authentic Italian cuisine in a cozy atmosphere",
  "category": "Bangladeshi",
  "hasDelivery": true,
  "contactEmail": "info@bellaitalia.com",
  "contactNumber": "555-123-4567",
  "city": "New York",
  "street": "123 Main Street",
  "postalCode": "10001"
}

###
GET https://localhost:7173/api/Restaurants/3

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "Name": "Bella Chao",
  "Description": "Authentic French cuisine in a cozy atmosphere.",
  "HasDelivery": false
}

###
